d_model: 20
n_classes: 10
img_size: [32, 32]
patch_size: [4, 4]
n_channels: 3
n_heads: 10
n_layers: 10
batch_size: 32
epochs: 100
alpha: 0.002
pos_tyep: "sinusiodal" #sinusiodal, 1d_learned, 2d_learned, "sinusiodal", "None"
