d_model: 20
n_classes: 10
img_size: [32, 32]
patch_size: [8, 8]
n_channels: 3
n_heads: 10
n_layers: 10
batch_size: 256
epochs: 100
alpha: 0.002
pos_type: "sinusoidal" #sinusoidal, 1d_learned, 2d_learned, "sinusiodal", "None"
aug_type: "mixing" #options: basic, mix, strong
